# Generated by Django 5.1.7 on 2025-08-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TT_ANABOLIC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': [('cadastrar_produto', 'Pode cadastrar produtos'), ('editar_produto', 'Pode editar produtos'), ('remover_produto', 'Pode remover produtos')]},
        ),
    ]
