# Generated by Django 5.1.7 on 2025-09-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT_ANABOLIC', '0003_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=1000, verbose_name='descricao'),
        ),
    ]
